package com.RAP.backend.rental.dto;

import com.RAP.backend.payment.PaymentGateway;
import com.RAP.backend.rental.EscrowStatus;
import com.RAP.backend.rental.RentalStatus;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public record RentalResponse(
		UUID id,
		UUID listingId,
		String listingTitle,
		String listingImage,
		BigDecimal dailyRate,
		BigDecimal deposit,
		BigDecimal commitmentFee,
		BigDecimal rentalTotal,
		BigDecimal payLater,
		BigDecimal remainingDue,
		boolean remainingPaid,
		int days,
		LocalDate startDate,
		LocalDate endDate,
		String meetupLocation,
		Double meetupLatitude,
		Double meetupLongitude,
		RentalStatus status,
		PaymentGateway paymentGateway,
		EscrowStatus escrowStatus,
		String escrowNote,
		String myQrPayload,
		UUID ownerId,
		String ownerName,
		String ownerAvatarUrl,
		UUID renterId,
		String renterName,
		String renterAvatarUrl,
		boolean owner,
		boolean renter,
		String renterNote,
		Instant createdAt,
		boolean canReview,
		Integer myRating,
		String myComment,
		Double renterRating,
		Long renterReviewCount,
		Long renterCompletedRentals,
		String renterCity,
		String returnMeetupLocation,
		Double returnMeetupLatitude,
		Double returnMeetupLongitude,
		Instant returnMeetupAt,
		boolean returnScheduled,
		String myReturnQrPayload,
		BigDecimal commitmentApplied,
		BigDecimal platformCommission,
		BigDecimal ownerPayout) {}
